### ISSUE TITLE
Step-level `notify` attribute fails schema validation

### ISSUE THREAD

**Issue by valeraz** [buildkite/pipeline-schema#18]
https://buildkite.com/docs/integrations/github#customizing-commit-statuses-step-level

<img width="673" alt="Screen Shot 2021-08-02 at 4 20 00 PM" src="https://user-images.githubusercontent.com/972173/127935211-66756965-1016-49c6-ac50-cd7a25d1dce0.png">

Using schema from "https://raw.githubusercontent.com/buildkite/pipeline-schema/master/schema.json"

**Comment by keith** [comment]
An attempt https://github.com/buildkite/pipeline-schema/pull/19
