### ISSUE TITLE
The soft_fail annotation is not included in the schema

### ISSUE THREAD

**Issue by DoomGerbil** [buildkite/pipeline-schema#2]
This was added as a valid keyword on jobs [a few weeks ago](https://buildkite.com/changelog/56-command-steps-can-now-be-made-to-soft-fail), but the schema doesn't include it yet, so my VSCode schema validator claims that it's invalid.  :(

**Comment by plasticine** [comment]
@DoomGerbil Thanks for the nudge, I’ll see if I can work out how to fix this! 😅
