### ISSUE TITLE
YAML named anchors always show up as invalid according to the schema validator

### ISSUE THREAD

**Issue by DoomGerbil** [buildkite/pipeline-schema#3]
I'm unsure if this is something that comes up as invalid based on the schema, or if this is because the [schema validation plugin](https://github.com/redhat-developer/vscode-yaml) I'm using in VSCode doesn't know how to deal with them, but our BuildKite pipelines use a lot of YAML named anchors, and they all appear as invalid, as below:

![Screenshot 2019-07-02 at 14 08 49](https://user-images.githubusercontent.com/1924264/60515350-546d6a00-9cd3-11e9-88b8-60d3205f5c50.png)

Is this something that can be fixed in the schema, or is this a bug for the plugin?

**Comment by toolmantim** [comment]
Ah, sorry you hit that. I believe we just need to allow unknown keys in the schema by removing the last line in https://github.com/buildkite/pipeline-schema/blob/master/schema.json.

Would happily accept a PR with a test case if you wanted to give it a go?

**Comment by DoomGerbil** [comment]
> Ah, sorry you hit that. I believe we just need to allow unknown keys in the schema by removing the last line in https://github.com/buildkite/pipeline-schema/blob/master/schema.json.
> 
> Would happily accept a PR with a test case if you wanted to give it a go?

I'll take a swing at this when I have a chance this week.  Thanks!

**Comment by DoomGerbil** [comment]
@toolmantim I finally got around to this, and opened https://github.com/buildkite/pipeline-schema/pull/5.  Thanks!  :)
