### ISSUE TITLE
concurrency_method step field looks to be missing

### ISSUE THREAD

**Issue by jlisee** [buildkite/pipeline-schema#36]
Is `concurrency_method` step field a valid one?  You can pass it to buildkite, and it is [mentioned in the example here](https://buildkite.com/docs/pipelines/controlling-concurrency#concurrency-and-parallelism-controlling-command-order).  But it's not otherwise documented and it's not in the schema itself.

**Comment by jlisee** [comment]
From talking to support I got the following information:

>concurrency_method is a valid step field, though it is optional.
>
>There are two options for the concurrency method: Ordered and Eager.
>
>By default, the concurrency group will use the Ordered method, unless you specify eager as the concurrency_method in the step.

**Comment by jlisee** [comment]
I have attempted add this in https://github.com/buildkite/pipeline-schema/pull/38

**Comment by sj26** [comment]
Thanks! #38 is merged.
