### ISSUE TITLE
Inconsistent pattern for using underscores in "key" attribute

### ISSUE THREAD

**Issue by andrew-boyad** [buildkite/pipeline-schema#37]
When creating a step, values with underscores are allowed when using the `key` attribute.
This is confirmed by https://github.com/buildkite/feedback/issues/424

In the schema json, the pattern for `key` does not explicitly support underscores.
https://github.com/buildkite/pipeline-schema/blob/9d1f70f8a8849a98f348dd91bc81964ad04eeddd/schema.json#L286

Should the schema's pattern explicitly support underscores in the `key` attribute?

**Comment by sj26** [comment]
Yes, you're right! Happy to merge a patch.

**Comment by mhaylock** [comment]
Fixed in #45
