### ISSUE TITLE
Inconsistencies between documentation and schema

### ISSUE THREAD

**Issue by franklin-ross** [buildkite/pipeline-schema#44]
According to the [docs](https://buildkite.com/docs/pipelines/group-step#group-step-attributes) the `group` field is allowed to be `null` but in the schema it appears to be non-nullable.

**Comment by franklin-ross** [comment]
Found another few fields in the docs (listed earlier) but not the schema.

**In the docs but not the schema:** `allow_dependency_failure`, `notify`

**Comment by franklin-ross** [comment]
I'd also love to know what the expected behaviour is for the fields that alias each other. What happens if I specify more than 1 and they have different values?

- `group`, `label`, `name`
- `key`, `id`, `identifier`

**Comment by scadu** [comment]
Another thing is `steps` which is required, but not defined as required in the schema.
