### ISSUE TITLE
Group is missing `if`

### ISSUE THREAD

**Issue by lxfontes** [buildkite/pipeline-schema#54]
👋  hello!

`groupStep` is missing the `if` attribute.
<img width="758" alt="Screenshot 2023-03-08 at 10 13 38 AM" src="https://user-images.githubusercontent.com/35205/223751834-e47ec30e-c93c-4f66-a6dc-df294f06c31f.png">

**Comment by Tyler-2** [comment]
I dropped a PR for this but I have no idea how to get it approved.

In the meantime... you can save:
https://github.com/buildkite/pipeline-schema/blob/ab7c7ab8872a3ac63e693e080426a63c15a728d4/schema.json

to a local place and then open up your VSCode or VSCodium settings and navigate to Settings, Extensions, YAML, Yaml: Schemas, "Edit in settings.json".

And then add something like:

```
    "yaml.schemas": {
        
        "/home/someuser/unnecessarydownloads/schema.json": "pipeline.yml"

    },
```

Which will tell the yaml language server to use that schema.json for files named `pipeline.yml`.
