### ISSUE TITLE
Conditionals cause pipeline.yml to fail validation

### ISSUE THREAD

**Issue by Redapted** [buildkite/pipeline-schema#7]
### Problem

Using a conditional in a `pipeline.yml` file causes validation to fail with the following message: `Property if is not allowed.`. Shown here using the example from the Buildkite documentation, [Using Conditionals](https://buildkite.com/docs/pipelines/conditionals):

![Screen Shot 2020-01-08 at 14 44 22](https://user-images.githubusercontent.com/3004637/72022600-b5976c80-3225-11ea-9689-16fc5fd0da07.png)
![Screen Shot 2020-01-08 at 14 56 53](https://user-images.githubusercontent.com/3004637/72023247-212e0980-3227-11ea-8866-30fa9de8b3ce.png)

### Suspected Cause

It appears as though the schema does not currently support the `if` property. The [`schema.json`](https://github.com/buildkite/pipeline-schema/blob/2c18e8804041eab0989afd3e5d28159bce5838a3/schema.json) does not have any attribute `"if"` within the [`commandStep`](https://github.com/buildkite/pipeline-schema/blob/2c18e8804041eab0989afd3e5d28159bce5838a3/schema.json#L238-L456).

Conditional properties were introduced approximately [three months ago](https://buildkite.com/changelog/76-conditional-expressions-for-pipeline-steps), so it seems likely that the schema simply has not yet been updated.

### Suggested Fix

It seems likely that the fix will be similar to that in #4. This case may be simpler, as the documentation indicates only strings are supported by this property.

**Comment by nchlswhttkr** [comment]
Any chance this might have been fixed by #6? It was just merged this morning.

**Comment by Redapted** [comment]
@nchlswhttkr Looks like the actual merge took place almost exactly 5 minutes after I submitted this. Fastest turnaround on an issue ever 😄
Thanks for handling; much appreciated.
